// ═══════════════════════════════════════════════════════════════════════════
//  menu-items.js — 完整五語言渲染資料 (ZAC CAFE)
//  語言：繁體中文 / English / 日本語 / 한국어 / Español
// ═══════════════════════════════════════════════════════════════════════════

export const storeInfo = {
  names: {
    zh: 'ZAC 咖啡',
    en: 'ZAC CAFE',
    de: 'ZAC CAFÉ',
    fr: 'ZAC CAFÉ',
    es: 'CAFÉ ZAC',
  },
  since: '1997',
  address: {
    zh: '977 花蓮縣豐濱鄉靜浦村8-1號',
    en: 'No. 8-1, Jingpu Village, Fengbin Township, Hualien County 977',
    de: 'Nr. 8-1, Dorf Jingpu, Gemeinde Fengbin, Landkreis Hualien 977',
    fr: 'N° 8-1, Village Jingpu, Canton Fengbin, Comté de Hualien 977',
    es: 'N.º 8-1, Aldea Jingpu, Municipio Fengbin, Condado de Hualien 977',
  },
  phone: '03-425-1598',
  hours: {
    zh: '13:00 – 21:00',
    en: '13:00 – 21:00',
    de: '13:00 – 21:00',
    fr: '13:00 – 21:00',
    es: '13:00 – 21:00',
  },
  reservation: {
    zh: '訂位專線',
    en: 'Reservation',
    de: 'Reservierung',
    fr: 'Réservation',
    es: 'Reservas',
  },
};

export const categories = [
  {
    id: 'snack',
    label: { zh: '零嘴小點', en: 'Snacks', de: 'Snacks', fr: 'Snacks', es: 'Aperitivos' },
  },
  {
    id: 'pie',
    label: { zh: '鹹派 & 甜塔', en: 'Pies & Tarts', de: 'Kuchen & Tartes', fr: 'Quiches & Tartes', es: 'Quiches & Tartas' },
  },
  {
    id: 'set',
    label: { zh: '精選套餐', en: 'Select Sets', de: 'Ausgewählte Menüs', fr: 'Menus Sélectés', es: 'Menús Selectos' },
  },
  {
    id: 'combo',
    label: { zh: '組合套餐', en: 'Combo Sets', de: 'Kombis', fr: 'Combos', es: 'Combos' },
  },
  {
    id: 'bread',
    label: { zh: '經典軟法', en: 'Classic Baguette', de: 'Klassisches Baguette', fr: 'Baguettes Classiques', es: 'Baguettes Clásicas' },
  },
];

export const tagDefs = {
  R:  { icon: '⭐', zh: '本店推薦', en: 'Recommended',              es: 'Recomendado' },
  1:  { icon: '🌶️', zh: '小辣',   en: 'Mild Spicy',         es: 'Poco picante' },
  2:  { icon: '🌶️🌶️', zh: '中辣',en: 'Medium Spicy',         es: 'Medio picante' },
  3:  { icon: '🔥', zh: '大辣',   en: 'Very Spicy',         es: 'Muy picante' },
  P:  { icon: '🐷', zh: '含豬肉', en: 'Contains Pork',     es: 'Contiene cerdo' },
  B:  { icon: '🐂', zh: '含牛肉', en: 'Contains Beef',       de: 'Enthält Rindfleisch',           fr: 'Contient du bœuf',          es: 'Contiene ternera' },
  L:  { icon: '🐑', zh: '含羊肉', en: 'Contains Lamb',       de: 'Enthält Lammfleisch',           fr: "Contient de l'agneau",     es: 'Contiene cordero' },
  V:  { icon: '🥬', zh: '素食',   en: 'Vegetarian',              es: 'Vegetariano' },
  V5: { icon: '🧄', zh: '五辛素', en: 'Plant-based with Allium',  es: 'Vegetal con aliáceas' },
  H:  { icon: '☪️', zh: '清真',   en: 'Halal',              es: 'Halal' },
};

export const menuItems = [
  // ── 零嘴小點 ──
  {
    id: 'snack-001',
    category: 'snack',
    names: {
      zh: '奶油爆米花',
      en: 'Butter Popcorn',
      de: 'Butterpopkorn',
      fr: 'Popcorn au Beurre',
      es: 'Palomitas con Mantequilla',
    },
    price: [{ label: null, value: 100 }],
    image: null,
    emoji: '🍿',
    tags: [],
    desc: { zh: '', en: '', de: '', fr: '', es: '' },
    note: {
      zh: '鹽子彈爆米花，讓你好好下酒！一份常常難以控制！',
      en: 'Salt-bomb popcorn — the perfect snack with drinks. One portion is never enough!',
      de: 'Salziges Knallbomben-Popcorn — der perfekte Snack zu Getränken. Eine Portion reicht nie!',
      fr: 'Popcorn ultra-salé — le snack parfait avec des boissons. Une portion ne suffit jamais !',
      es: 'Palomitas con mucha sal, perfectas para acompañar bebidas. ¡Una ración nunca es suficiente!',
    },
  },
  {
    id: 'snack-002',
    category: 'snack',
    names: {
      zh: '火腿起司歐姆蛋',
      en: 'Ham & Cheese Omelette',
      de: 'Schinken-Käse-Omelett',
      fr: 'Omelette Jambon-Fromage',
      es: 'Tortilla de Jamón y Queso',
    },
    price: [{ label: null, value: 300 }],
    image: null,
    emoji: '🍳',
    tags: [],
    desc: { zh: '', en: '', de: '', fr: '', es: '' },
    note: {
      zh: '鮮軟蛋捲搭配越南豬肉火腿與濃郁起司，透有隱約的香氣天然甜感加上奶香風。',
      en: 'Silky egg wrap with Vietnamese-style ham and rich cheese, subtly fragrant with a natural sweetness and creamy finish.',
      de: 'Seidiges Eiröllchen mit vietnamesischem Schinken und reichhaltigem Käse, dezent würzig mit natürlicher Süße.',
      fr: 'Omelette soyeuse au jambon vietnamien et fromage riche, subtilement parfumée avec une douceur naturelle.',
      es: 'Tortilla sedosa con jamón al estilo vietnamita y queso rico, con un sutil aroma y dulzura natural.',
    },
  },
  {
    id: 'snack-003',
    category: 'snack',
    names: {
      zh: '香烤蕃茄嫩雞翅',
      en: 'Tomato Herb Baked Chicken Wings',
      de: 'Tomaten-Kräuter-Hähnchenflügel',
      fr: 'Ailes de Poulet Tomate et Herbes',
      es: 'Alitas de Pollo al Tomate y Hierbas',
    },
    price: [{ label: null, value: 340 }],
    image: null,
    emoji: '🍗',
    tags: [],
    desc: { zh: '', en: '', de: '', fr: '', es: '' },
    note: {
      zh: '外表酥脆、香體脂肪低，並入特別的秘醬調味，散發誘人的天然香氣。',
      en: 'Crispy outside, tender inside, low in fat — marinated in our secret sauce with irresistible natural aromas.',
      de: 'Außen knusprig, innen zart — mariniert in unserer Geheimsauce mit unwiderstehlichen natürlichen Aromen.',
      fr: 'Croustillantes dehors, tendres dedans — marinées dans notre sauce secrète aux arômes naturels irrésistibles.',
      es: 'Crujientes por fuera, tiernas por dentro — marinadas en nuestra salsa secreta con aromas irresistibles.',
    },
  },
  {
    id: 'snack-004',
    category: 'snack',
    names: {
      zh: '乳酪起司四重奏',
      en: 'Four-Cheese Quartet',
      de: 'Vier-Käse-Quartett',
      fr: 'Quatuor de Fromages',
      es: 'Cuarteto de Quesos',
    },
    price: [{ label: null, value: 390 }],
    image: null,
    emoji: '🧀',
    tags: [],
    desc: { zh: '', en: '', de: '', fr: '', es: '' },
    note: {
      zh: '精選四款濃郁系乳酪，各切三角一片，搭配海鹽、奶香餅乾與巧克力品嘗。',
      en: 'Four rich cheeses, each sliced into wedges, served with sea salt, buttery crackers and chocolate.',
      de: 'Vier kräftige Käse in Spalten geschnitten, serviert mit Meersalz, Butterkeksen und Schokolade.',
      fr: 'Quatre fromages savoureux en quartiers, servis avec du sel marin, des crackers au beurre et du chocolat.',
      es: 'Cuatro quesos intensos en gajos, servidos con sal marina, galletas mantequilladas y chocolate.',
    },
  },

  // ── 鹹派 & 甜塔 ──
  {
    id: 'pie-001',
    category: 'pie',
    names: {
      zh: '培根乳酪派',
      en: 'Bacon & Cheese Quiche',
      de: 'Speck-Käse-Quiche',
      fr: 'Quiche Bacon et Fromage',
      es: 'Quiche de Bacon y Queso',
    },
    price: [{ label: null, value: 180 }],
    image: null,
    emoji: '🥧',
    tags: ['R'],
    desc: { zh: '', en: '', de: '', fr: '', es: '' },
    note: {
      zh: '桃山香薰肉片自製乳酪派，以新鮮乳酪融合，乳香入風。',
      en: 'House-made quiche with fragrant smoked bacon and fresh melted cheese — rich and aromatic.',
      de: 'Hausgemachte Quiche mit aromatischem Räucherspeck und frisch geschmolzenem Käse — reichhaltig und aromatisch.',
      fr: 'Quiche maison au bacon fumé parfumé et fromage fondu frais — riche et aromatique.',
      es: 'Quiche casera con bacon ahumado aromático y queso fresco fundido — rico y delicioso.',
    },
  },
  {
    id: 'pie-002',
    category: 'pie',
    names: {
      zh: '青花鮭魚鹹派',
      en: 'Salmon & Gorgonzola Quiche',
      de: 'Lachs-Gorgonzola-Quiche',
      fr: 'Quiche Saumon et Gorgonzola',
      es: 'Quiche de Salmón y Gorgonzola',
    },
    price: [{ label: null, value: 180 }],
    image: null,
    emoji: '🥧',
    tags: [],
    desc: { zh: '', en: '', de: '', fr: '', es: '' },
    note: {
      zh: '優質新鮮台灣花鮭，搭配藍起司乳酪自製配方，加入大量濃郁的奶香醬。',
      en: 'Fresh Taiwanese salmon paired with house blue-cheese blend, layered generously and finished with rich cream sauce.',
      de: 'Frischer taiwanesischer Lachs mit hausgemachter Blauschimmelkäsemischung, großzügig geschichtet und mit reichhaltiger Sahnesauce verfeinert.',
      fr: 'Saumon frais taïwanais avec mélange de fromage bleu maison, généreusement garni et nappé d\'une riche sauce crème.',
      es: 'Salmón fresco taiwanés con mezcla de queso azul de la casa, acabado con cremosa salsa.',
    },
  },
  {
    id: 'pie-003',
    category: 'pie',
    names: {
      zh: '焦糖海鹽核桃塔',
      en: 'Salted Caramel Walnut Tart',
      de: 'Gesalzene Karamell-Walnuss-Tarte',
      fr: 'Tarte Caramel Salé et Noix',
      es: 'Tarta de Nueces y Caramelo Salado',
    },
    price: [{ label: null, value: 180 }],
    image: null,
    emoji: '🍮',
    tags: [],
    desc: { zh: '', en: '', de: '', fr: '', es: '' },
    note: {
      zh: '特製焦糖液加入大量核桃碎，以海鹽平衡甜度，搭配入口即化的奶油塔皮。',
      en: 'House caramel with crushed walnuts, balanced with sea salt, on a melt-in-your-mouth butter crust.',
      de: 'Hausgemachtes Karamell mit gehackten Walnüssen, mit Meersalz ausbalanciert, auf einem schmelzenden Butterteig.',
      fr: 'Caramel maison avec des noix concassées, équilibré au sel marin, sur une pâte brisée au beurre qui fond en bouche.',
      es: 'Caramelo casero con nueces picadas, equilibrado con sal marina, sobre una masa de mantequilla que se deshace.',
    },
  },
  {
    id: 'pie-004',
    category: 'pie',
    names: {
      zh: '奶油蔬菜鹹派（凱薩醬／和風醬）',
      en: 'Creamy Veggie Quiche (Caesar / Wafu)',
      de: 'Cremige Gemüse-Quiche (Caesar / Wafu)',
      fr: 'Quiche Végétale Crémeuse (César / Wafu)',
      es: 'Quiche Vegetal Cremosa (César / Wafu)',
    },
    price: [{ label: null, value: 150 }],
    image: null,
    emoji: '🥧',
    tags: ['V'],
    desc: { zh: '', en: '', de: '', fr: '', es: '' },
    note: {
      zh: '大量新鮮蔬菜加入自製奶油白醬，搭配凱薩醬或和風醬，濃郁奶香包裹鮮甜蔬菜。',
      en: 'Loaded with fresh vegetables in house cream sauce — choose Caesar or Japanese wafu dressing.',
      de: 'Mit frischem Gemüse und hausgemachter Sahnesauce — Caesar- oder japanisches Wafu-Dressing wählbar.',
      fr: 'Garnie de légumes frais dans une sauce crémeuse maison — vinaigrette César ou japonaise wafu au choix.',
      es: 'Cargada de verduras frescas en salsa cremosa casera — elige aderezo César o japonés wafu.',
    },
  },
  {
    id: 'pie-005',
    category: 'pie',
    names: {
      zh: '香草檸檬塔',
      en: 'Lemon Herb Tart',
      de: 'Zitronen-Kräuter-Tarte',
      fr: 'Tarte Citron et Herbes',
      es: 'Tarta de Limón y Hierbas',
    },
    price: [{ label: null, value: 150 }],
    image: null,
    emoji: '🍋',
    tags: [],
    desc: { zh: '', en: '', de: '', fr: '', es: '' },
    note: {
      zh: '以新鮮檸檬汁加入法式特製奶油醬，佐以清爽的香草與酸甜清新感。',
      en: 'Fresh lemon curd on a French-style butter base, lifted with herbs and topped with fresh cream.',
      de: 'Frische Zitronencreme auf französischer Butterbasis, mit Kräutern aufgefrischt und mit frischer Sahne garniert.',
      fr: 'Crème au citron frais sur une base française au beurre, rehaussée d\'herbes et garnie de crème fraîche.',
      es: 'Crema de limón fresco sobre base francesa de mantequilla, realzada con hierbas y nata fresca.',
    },
  },

  // ── 精選套餐 ──
  {
    id: 'set-001',
    category: 'set',
    names: {
      zh: '蘿蔔牛腩燴飯',
      en: 'Braised Beef Brisket with Radish on Rice',
      de: 'Geschmorte Rinderbrust mit Rettich auf Reis',
      fr: 'Poitrine de Bœuf Braisée au Radis sur Riz',
      es: 'Arroz con Pecho de Ternera Estofado y Rábano',
    },
    price: [{ label: null, value: 260 }],
    image: null,
    emoji: '🍛',
    tags: ['B'],
    desc: { zh: '', en: '', de: '', fr: '', es: '' },
    note: {
      zh: '以蘿蔔、老薑、多種香料大火燉煮的牛腩，口感軟嫩帶有豐富湯汁。',
      en: 'Slow-braised beef brisket with daikon and ginger, tender and richly flavoured.',
      de: 'Langsam geschmorte Rinderbrust mit Daikon und Ingwer, zart und intensiv im Geschmack.',
      fr: 'Poitrine de bœuf braisée lentement avec du daikon et du gingembre, tendre et richement parfumée.',
      es: 'Pecho de ternera estofado a fuego lento con rábano daikon y jengibre, tierno y muy sabroso.',
    },
  },
  {
    id: 'set-002',
    category: 'set',
    names: {
      zh: '泰式綠咖哩雞肉飯',
      en: 'Thai Green Curry Chicken Rice',
      de: 'Thai-Grüncurry mit Hühnchen auf Reis',
      fr: 'Curry Vert Thaï au Poulet sur Riz',
      es: 'Arroz con Curry Verde Tailandés y Pollo',
    },
    price: [{ label: null, value: 280 }],
    image: null,
    emoji: '🍛',
    tags: ['R', '1'],
    desc: { zh: '', en: '', de: '', fr: '', es: '' },
    note: {
      zh: '道地泰式料理為基底，搭配特製椰奶香氣，加入大量新鮮蔬菜與嫩雞腿肉。',
      en: 'Authentic Thai base with fragrant coconut milk, fresh vegetables and tender chicken thigh.',
      de: 'Authentische Thai-Basis mit aromatischer Kokosmilch, frischem Gemüse und zartem Hähnchenschenkel.',
      fr: 'Base thaïlandaise authentique au lait de coco parfumé, légumes frais et tendre cuisse de poulet.',
      es: 'Base tailandesa auténtica con aromático coco, verduras frescas y tierno muslo de pollo.',
    },
  },
  {
    id: 'set-003',
    category: 'set',
    names: {
      zh: '義式蕃茄牛肉燴飯',
      en: 'Italian Tomato Beef Stew on Rice',
      de: 'Italienisches Tomaten-Rindfleisch auf Reis',
      fr: 'Bœuf à la Tomate Italienne sur Riz',
      es: 'Arroz con Estofado Italiano de Ternera y Tomate',
    },
    price: [{ label: null, value: 280 }],
    image: null,
    emoji: '🍝',
    tags: ['B'],
    desc: { zh: '', en: '', de: '', fr: '', es: '' },
    note: {
      zh: '道地義式料理為基底，搭配特製蕃茄醬汁，加入大量新鮮蔬菜以及嫩牛肉片。',
      en: 'Classic Italian-style tomato sauce with fresh vegetables and tender sliced beef over rice.',
      de: 'Klassische italienische Tomatensauce mit frischem Gemüse und zarten Rindfleischstreifen auf Reis.',
      fr: 'Sauce tomate italienne classique avec légumes frais et tranches de bœuf tendres sur riz.',
      es: 'Salsa de tomate al estilo italiano clásico con verduras frescas y tiernas lonchas de ternera sobre arroz.',
    },
  },
  {
    id: 'set-004',
    category: 'set',
    names: {
      zh: '牛肉千層麵',
      en: 'Beef Lasagne',
      de: 'Rinderlasagne',
      fr: 'Lasagne au Bœuf',
      es: 'Lasaña de Ternera',
    },
    price: [{ label: null, value: 280 }],
    image: null,
    emoji: '🍝',
    tags: ['B'],
    desc: { zh: '', en: '', de: '', fr: '', es: '' },
    note: {
      zh: '道地義式千層麵，搭配特製番茄肉醬，加入大量新鮮蔬菜以及嫩牛肉片。',
      en: 'Classic Italian lasagne layered with house bolognese, fresh vegetables and tender beef.',
      de: 'Klassische italienische Lasagne mit hausgemachter Bolognese, frischem Gemüse und zartem Rindfleisch.',
      fr: 'Lasagne italienne classique en couches avec bolognaise maison, légumes frais et bœuf tendre.',
      es: 'Lasaña italiana clásica con boloñesa casera, verduras frescas y ternera tierna en capas.',
    },
  },
  {
    id: 'set-005',
    category: 'set',
    names: {
      zh: '煎煎小羊排拼飯',
      en: 'Pan-Seared Lamb Chop Plate',
      de: 'Gebratene Lammkoteletts',
      fr: 'Côtelettes d\'Agneau Poêlées',
      es: 'Chuletas de Cordero a la Sartén',
    },
    price: [{ label: null, value: 300 }],
    image: null,
    emoji: '🍖',
    tags: ['L', 'R'],
    desc: { zh: '', en: '', de: '', fr: '', es: '' },
    note: {
      zh: '精選紐西蘭羔羊排，以特製香料醃製，煎出外酥內嫩的完美口感。',
      en: 'New Zealand lamb chops marinated in house spices, pan-seared to a crisp exterior with a juicy centre.',
      de: 'Neuseeländische Lammkoteletts in Hausgewürzen mariniert, außen knusprig und innen saftig gebraten.',
      fr: 'Côtelettes d\'agneau de Nouvelle-Zélande marinées aux épices maison, dorées à la poêle — croustillantes dehors, juteuses dedans.',
      es: 'Chuletas de cordero de Nueva Zelanda marinadas en especias caseras, doradas por fuera y jugosas por dentro.',
    },
  },

  // ── 組合套餐 ──
  {
    id: 'combo-001',
    category: 'combo',
    names: {
      zh: '鹹甜好滋味',
      en: 'Sweet & Savory Duo',
      de: 'Süß-herzhaftes Duo',
      fr: 'Duo Sucré-Salé',
      es: 'Dúo Dulce y Salado',
    },
    price: [{ label: null, value: 565 }],
    image: null,
    emoji: '🍽️',
    tags: [],
    desc: { zh: '', en: '', de: '', fr: '', es: '' },
    note: {
      zh: '鹹派精選（NT.180）+ 甜塔一個（NT.150），鹹甜雙重享受！',
      en: 'One savory quiche (NT.180) + one sweet tart (NT.150) — the best of both worlds.',
      de: 'Eine herzhafte Quiche (NT.180) + eine süße Tarte (NT.150) — das Beste aus beiden Welten.',
      fr: 'Une quiche salée (NT.180) + une tarte sucrée (NT.150) — le meilleur des deux mondes.',
      es: 'Una quiche salada (NT.180) + una tarta dulce (NT.150) — lo mejor de los dos mundos.',
    },
  },
  {
    id: 'combo-002',
    category: 'combo',
    names: {
      zh: '雙享好滿足',
      en: 'Double Delight Set',
      de: 'Doppeltes Vergnügen',
      fr: 'Double Plaisir',
      es: 'Set Doble Placer',
    },
    price: [{ label: null, value: 536 }],
    image: null,
    emoji: '🍽️',
    tags: [],
    desc: { zh: '', en: '', de: '', fr: '', es: '' },
    note: {
      zh: '選購主餐1份（NT.180以上）＋鹹派甜塔任選一，雙重體驗！',
      en: 'Choose 1 main (NT.180+) + any quiche or tart — the ultimate combo experience.',
      de: '1 Hauptgericht (NT.180+) + eine beliebige Quiche oder Tarte — das ultimative Kombi-Erlebnis.',
      fr: 'Choisissez 1 plat principal (NT.180+) + n\'importe quelle quiche ou tarte — l\'expérience combo ultime.',
      es: 'Elige 1 plato principal (NT.180+) + cualquier quiche o tarta — la combinación perfecta.',
    },
  },

  // ── 經典軟法 ──
  {
    id: 'bread-001',
    category: 'bread',
    names: {
      zh: '香蒜軟法',
      en: 'Garlic Butter Baguette',
      de: 'Knoblauch-Butter-Baguette',
      fr: 'Baguette à l\'Ail et au Beurre',
      es: 'Baguette de Ajo y Mantequilla',
    },
    price: [{ label: null, value: 220 }],
    image: null,
    emoji: '🥖',
    tags: ['V'],
    desc: { zh: '', en: '', de: '', fr: '', es: '' },
    note: {
      zh: '以自製蒜香奶油抹醬烤製，外表酥脆內裡鬆軟，入口充滿濃郁蒜香與奶油香氣。',
      en: 'Baked with house garlic butter spread — crispy crust, fluffy inside, rich in garlic and butter.',
      de: 'Mit hausgemachter Knoblauchbutter gebacken — knusprige Kruste, fluffiges Inneres, reich an Knoblauch und Butter.',
      fr: 'Cuite avec du beurre à l\'ail maison — croûte croustillante, intérieur moelleux, riche en ail et beurre.',
      es: 'Horneada con mantequilla de ajo casera — corteza crujiente, interior esponjoso, rico en ajo y mantequilla.',
    },
  },
  {
    id: 'bread-002',
    category: 'bread',
    names: {
      zh: '蜜芝麻乳酪軟法',
      en: 'Honey Sesame Cheese Baguette',
      de: 'Honig-Sesam-Käse-Baguette',
      fr: 'Baguette Miel, Sésame et Fromage',
      es: 'Baguette de Miel, Sésamo y Queso',
    },
    price: [{ label: null, value: 300 }],
    image: null,
    emoji: '🥖',
    tags: [],
    desc: { zh: '', en: '', de: '', fr: '', es: '' },
    note: {
      zh: '蜂蜜芝麻與濃郁乳酪融合，外酥內軟，甜香的蜂蜜加上芝麻香氣。',
      en: 'Sweet honey and sesame melded with rich cheese — crispy outside, soft inside.',
      de: 'Süßer Honig und Sesam mit reichhaltigem Käse verschmolzen — außen knusprig, innen weich.',
      fr: 'Miel doux et sésame fondus avec du fromage riche — croustillant dehors, moelleux dedans.',
      es: 'Miel dulce y sésamo fusionados con queso rico — crujiente por fuera, suave por dentro.',
    },
  },
  {
    id: 'bread-003',
    category: 'bread',
    names: {
      zh: '煙燻雞肉起司軟法',
      en: 'Smoked Chicken & Cheese Baguette',
      de: 'Geräuchertes Hühnchen & Käse-Baguette',
      fr: 'Baguette Poulet Fumé et Fromage',
      es: 'Baguette de Pollo Ahumado y Queso',
    },
    price: [{ label: null, value: 320 }],
    image: null,
    emoji: '🥖',
    tags: [],
    desc: { zh: '', en: '', de: '', fr: '', es: '' },
    note: {
      zh: '以煙燻雞肉加上濃郁起司烤製，外酥內軟，煙燻香氣與起司香氣完美融合。',
      en: 'Smoked chicken and melted cheese baked into a crusty baguette — smoky, rich and satisfying.',
      de: 'Geräuchertes Hühnchen und geschmolzener Käse in ein knuspriges Baguette gebacken — rauchig, reichhaltig und sättigend.',
      fr: 'Poulet fumé et fromage fondu cuits dans une baguette croustillante — fumé, riche et satisfaisant.',
      es: 'Pollo ahumado y queso fundido horneados en una baguette crujiente — ahumada, rica y satisfactoria.',
    },
  },
];
